name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Get
      run: go get -v

    - name: Test
      run: go test -v ./... -covermode=count -coverprofile=coverage.out

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
